### PR TITLE
Fixes tursodatabase/turso-driver-laravel#7

### PR DESCRIPTION
**Pull request by ineersa**
added inTransaction method for compatibility with PDO

### CODE REVIEW

**Comment by darkterminal** [comment]
Sorry, I am bit confused here. About issues #7, #9, #10, and #11.

I've Laravel example also [here](https://github.com/tursodatabase/examples/pull/2/files) And it's work.

Please provide a clear context for your case in each issue made. Since this is confusing me once again, I am working and trying to integrate Tenancy for Laravel and before that, I also used commands like:

```bash
php artisan migrate
php artisan migrate:fresh
php artisan migrate:rollback
```

It's working fine in Local, Remote, and Embedded Replica connection. Btw, still you have put a lot of time into this, thank you. However, I still need clear context. And once again, the **libSQL Extension** I created is **not built with the PDO engine**, it's a pure libSQL driver that wraps the libSQL binary from Turso written in Rust.

**Comment by ineersa** [comment]
Hi, those issues are things which are not working in driver, since I'm building an app I thought it would be good to make issues and PR's where i can make them, like in this case.
This PR fixes transaction rollback, which is not working in current version.
I've tried to describe problems in issues, also https://github.com/ineersa/turso-driver-laravel/tree/dev-branch dev branch because I need a lot of fixes, if you have questions regarding issues I'm free to discuss them.

```
It's working fine in Local, Remote, and Embedded Replica connection
```
For me sadly it's not like that, I'm having issues using it, some of which are really hard to fix and need intervention into extension (like there is no SQL errors), so maybe it would be better to fix this package issues and test things out before integrating it into some other packages?

**Comment by darkterminal** [comment]
I will update the `main` branch, because I made changes while trying to integrate Tenancy for Laravel. About broken things happen, it's true.

After I push some changes in the `main` branch, maybe you can adjust your connection. I've been working on it for almost 2 weeks.

**Comment by ineersa** [comment]
> I will update the `main` branch, because I made changes while trying to integrate Tenancy for Laravel. About broken things happen, it's true.
> 
> After I push some changes in the `main` branch, maybe you can adjust your connection. I've been working on it for almost 2 weeks.

For this it won't be a problem this changes are quite small, but for https://github.com/tursodatabase/turso-driver-laravel/pull/5 it might be, let's see what conflicts will be.

**Comment by darkterminal** [comment]
Yes, we'll see it...

**Pull request merged**
